#!/usr/bin/env python3
"""DEV-DOCS-INDEX.md is a VIEW, computed from the artifacts - never a file anyone appends to.

<!-- route-tags: dev docs index generate view planned development doc discovery duplicate sprawl -->
<!-- cornerstone: knowledge-routing -->

WHY THIS EXISTS, AND WHAT IT COST TO LEARN
------------------------------------------
Project CLAUDE.md, the human 2026-08-17: *"if it's an index, it must be generated, never hand-kept in
any way."* DEV-DOCS-INDEX was the last hand-kept one, and it had already drifted the way every
hand-kept index in this workspace has: on 2026-08-12 four of its rows pointed at
`docs/superpowers/specs/`, a directory the files had been moved out of, and the correction lived
on `main` while the branch a lane was reading had the wrong paths still.

⭐ THE TEST THAT MADE IT A DOCUMENT RATHER THAN AN INDEX: *if deleting the file would lose
information, it was never an index.* Deleting it used to lose 82 authored summaries that existed
nowhere else. Now it loses nothing - every summary lives ON the artifact it describes, and this
script rebuilds the file from them.

WHERE EACH PART LIVES, AND WHY THERE
------------------------------------
  MEMBERSHIP + PATH   derived, every run. An artifact is in the index because it CARRIES a
                      `<!-- dev-doc: ... -->` marker, and its path is where the file actually
                      is. A doc that moves takes its row with it; that is the whole point.
  THE SUMMARY         authored, and it lives ON THE ARTIFACT (`<!-- summary: ... -->`). It is
                      judgement and cannot be generated, so it is kept where it cannot be
                      separated from the thing it describes.
  SECTIONS + PROSE    authored, in `dev_docs_sections.json` beside this script - the same
                      ENGINE/VOCABULARY split as knowledge_pages.py and facets.py. A section
                      grouping is a claim about the business, not a fact about the corpus.

THE MARKER BLOCK an artifact carries
------------------------------------
    <!-- dev-doc: section=<slug> order=<n> [parent=<basename>] [path=<shown>] [url=<href>]
                  [also=<extra file>] -->
    <!-- dev-doc-title: <plain text title> -->
    <!-- summary: <the row's authored text: type, summary, status> -->

⛔ ORPHANS ARE PRINTED, NOT DROPPED. Three rows named artifacts that are on no branch of the
working tree (one is an unmerged PR; two exist in no commit anywhere). Their authored text is
held in the JSON's `orphans` list and rendered with a visible warning, because a row that
quietly disappears is exactly the data loss this conversion was told to avoid. When the file
appears, `--check` says so and the text moves onto it.

    dev_docs_index.py            report drift; write nothing (exit 1 if the view is stale)
    dev_docs_index.py --write    regenerate DEV-DOCS-INDEX.md
    dev_docs_index.py --check    orphan/marker health: unresolved orphans, unknown sections
    dev_docs_index.py --selftest

ASCII output. Fails loudly rather than writing a partial index.
"""
import argparse
import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from workspace_paths import WS, MEM  # noqa: E402
from mentions import declaration_region, outside_fences  # noqa: E402 - ONE definition

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

OUT = WS / "DEV-DOCS-INDEX.md"
DATA_FILE = Path(__file__).resolve().parent / "dev_docs_sections.json"

BANNER = ("<!-- GENERATED by .shared/scripts/dev_docs_index.py - do not hand-edit. "
          "A row's summary lives ON its artifact as `<!-- summary: ... -->`; the section "
          "groupings live in dev_docs_sections.json beside that script. -->")

# ⛔ ONE DEFINITION, MATCHED BY SHAPE. A marker format is a contract between every tool that
# reads it (`memory/marker_format_is_a_contract.md`), so anything else that wants these reads
# them from here rather than carrying a second regex that can drift.
#
# ⛔ ANCHORED TO COLUMN 0, BECAUSE A QUOTATION IS NOT A DECLARATION. This lane's own mailbox
# report described the marker inside a table cell and was promptly harvested as an artifact
# declaring section `None`. Anything that MENTIONS the syntax - a spec, a report, this file's
# own docstring - does so inline or indented; only the stamped block sits at the line start.
# Same defect route.py fixed by not counting a receipt shown inside a code fence.
DEV_DOC = re.compile(r"^<!--\s*dev-doc:\s*(?P<attrs>[^>]*?)\s*-->", re.M)
DEV_TITLE = re.compile(r"<!--\s*dev-doc-title:\s*(?P<t>.+?)\s*-->", re.S)
SUMMARY = re.compile(r"<!--\s*summary:\s*(?P<s>.+?)\s*-->", re.S)

# Directories that hold no knowledge and cost seconds to walk.
SKIP_DIRS = {"node_modules", ".git", "dist", "build", ".next", ".astro", "coverage",
             "__pycache__", ".venv", "venv", ".codesight", "out", ".turbo", ".cache",
             "voice_notes", "research_log"}


def _load():
    try:
        return json.loads(DATA_FILE.read_text(encoding="utf-8"))
    except Exception as e:                       # a missing shape is a real state, not a crash
        print("dev-docs index: cannot read %s (%s)" % (DATA_FILE.name, e), file=sys.stderr)
        return {}


DATA = _load()
SECTIONS = DATA.get("sections", [])
SECTION_ORDER = {s["slug"]: i for i, s in enumerate(SECTIONS)}


def collapse(s):
    return re.sub(r"\s+", " ", s).strip()


def read_markers(text):
    """{attrs, title, summary} for a marked artifact, or None. The ONE reader of the block."""
    m = DEV_DOC.search(text)
    if not m:
        return None
    attrs = {}
    for kv in m.group("attrs").split():
        if "=" in kv:
            k, v = kv.split("=", 1)
            attrs[k] = v
    t = DEV_TITLE.search(text)
    s = SUMMARY.search(text)
    return {"attrs": attrs,
            "title": collapse(t.group("t")) if t else None,
            "summary": collapse(s.group("s")) if s else None}


def harvest():
    """Every artifact carrying the marker, under the workspace or the memory store."""
    found = []
    for base in (WS, MEM):
        if not base.exists():
            continue
        for root, dirs, files in os.walk(base):
            # Name-set first because it is free; then the path check, which is the only one
            # that can recognise a worktree - their basenames are generated and unguessable.
            dirs[:] = [d for d in dirs
                       if d not in SKIP_DIRS and not _in_other_worktree(os.path.join(root, d))]
            for f in files:
                if not f.endswith(".md"):
                    continue
                p = Path(root) / f
                # ⛔ NEVER HARVEST A GENERATED VIEW, STARTING WITH THIS SCRIPT'S OWN OUTPUT.
                # The index quotes the marker syntax in its own header prose, so the first run
                # read the file it had just written and reported it as an artifact declaring
                # section `...`. A view that lists itself is the beginning of a loop.
                if p == OUT:
                    continue
                try:
                    raw = p.read_text(encoding="utf-8", errors="replace")
                except OSError:
                    continue
                # ⛔ A MARKER PAST 8000 CHARACTERS WAS STILL A MARKER, and this reader's
                # number was its own - route.py used 3000, knowledge_gate 4000 - so a doc could
                # be routable and absent from this index with nothing reporting the difference.
                # `declaration_region` answers it once for every reader; fences are stripped so
                # a doc TEACHING the marker syntax does not index itself, which is the same
                # hazard the self-exclusion above guards from the other direction.
                head = outside_fences(declaration_region(raw, p))
                if "\n<!-- dev-doc:" not in head and not head.startswith("<!-- dev-doc:"):
                    continue
                if "<!-- GENERATED by" in head[:400]:
                    continue
                mk = read_markers(head)
                if mk:
                    found.append({"path": p, **mk})
    return found


def _linkable(p):
    """Inside the <your-workspace> repo itself - i.e. no intervening `.git` on the way down.

    ⛔ A LINK THAT DOES NOT OPEN IS WORSE THAN NO LINK. The preview pane can only follow a
    relative path inside this repo; a nested product repo or the memory store is somewhere else
    on disk, so those render as plain text plus their absolute path, exactly as the hand-kept
    file did.
    """
    try:
        rel = p.relative_to(WS)
    except ValueError:
        return None
    parts = rel.as_posix().split("/")
    for k in range(1, len(parts)):
        if (WS.joinpath(*parts[:k]) / ".git").exists():
            return None
    return rel.as_posix()


def _reader_ws():
    """The MAIN working tree - where a reader opens these files, not where we are generating.

    ⛔ `WS` resolves to the repo the CALLER is in, deliberately: a gate acting on the caller's
    tree must see that tree. But an INDEX is read somewhere else. Regenerating from a worktree
    wrote that worktree into every row - measured at 42 of 59 rows on origin/main - so the map
    the human opens pointed into a directory that exists only while that worktree does.

    ⭐ One constant was answering two questions. "Where am I working" and "where does the reader
    open this" are different, and only the second belongs in a row.
    """
    try:
        import subprocess
        r = subprocess.run(["git", "worktree", "list", "--porcelain"],
                           capture_output=True, text=True, timeout=15, cwd=str(WS))
        for line in r.stdout.split("\n"):
            if line.startswith("worktree "):
                return Path(line[len("worktree "):].strip())
    except Exception:
        pass
    return WS


READER_WS = _reader_ws()


def _other_worktree_roots():
    """Every registered worktree EXCEPT the one a reader opens - the directories to never walk.

    ⛔ MEASURED 2026-09-08, reported by o1: DEV-DOCS-INDEX.md carried 91 rows pointing inside
    `.claude/worktrees/*` and `.wt-*`. Same artifact listed two and three times, at paths that
    vanish with the worktree - the exact failure the index rule names.

    ⭐ `_reader_ws()` above already fixed the SIBLING of this and its docstring says so: it stops
    a worktree being written INTO every row when generating FROM one. This is generating INTO a
    worktree, one level over, and the authoritative list was already in the call it makes - it
    just took the first line and dropped the rest.

    ⛔ WHY A NAME-SET CANNOT DO THIS. `SKIP_DIRS` matches `d not in SKIP_DIRS`, so it would need
    every worktree's basename - and those are generated (`nostalgic-hermann-495856`,
    `.wt-o8L131-at-audit`) and change every time one is created. Pruning by RESOLVED PATH against
    git's own list is the only version that stays true.

    ⚠️ Only worktrees NESTED INSIDE the walk root can be reached at all; the ones under
    `<your-workspace>-worktrees/` are siblings and were never the problem. Both are pruned anyway,
    because which are nested is a fact about today's layout.
    """
    roots = set()
    try:
        import subprocess
        r = subprocess.run(["git", "worktree", "list", "--porcelain"],
                           capture_output=True, text=True, timeout=15, cwd=str(WS))
        main = None
        for line in r.stdout.split("\n"):
            if not line.startswith("worktree "):
                continue
            p = Path(line[len("worktree "):].strip())
            if main is None:
                main = p.resolve()
                continue
            try:
                roots.add(p.resolve())
            except OSError:
                continue
    except Exception:
        pass                       # no git, no prune - the walk is then what it always was
    return roots


OTHER_WORKTREES = _other_worktree_roots()


def _is_worktree_dir(path):
    """True when this directory is a WORKTREE of some repo rather than a repo of its own.

    ⛔ THE REGISTRY GOES STALE, AND THE PRUNE ABOVE TRUSTS IT. o1 found two phantom rows return
    from `.wt-feature-test` and `wt-o10L50f`: both carry their own `.git`, and NEITHER appears
    in `git worktree list --porcelain`. So they are orphaned or detached, and a prune keyed on
    git's registration cannot see them.

    ⭐ THAT IS THE SHAPE THIS FILE ALREADY CARRIES A FIX FOR, landing on the fix itself. Asking
    git "what are your worktrees?" gets a truthful answer ABOUT ITS OWN REGISTRY, which is not
    the question "what worktree-shaped directories exist here". An instrument answering about
    itself, one level up from the last time.

    ⛔ o1's proposed distinguisher - a worktree shares `origin` with the workspace, a product
    repo does not - was offered as a guess and MEASURED WRONG: it matched 0 of them, because an
    orphaned worktree has no usable origin at all and therefore sorts with the product repos.
    Their instinct to flag it as a guess was right.

    ⭐ The structural property is exact and needs no git process: git leaves a worktree a `.git`
    FILE containing `gitdir: ...`, while a real repository has a `.git` DIRECTORY. Measured
    across this workspace: 17 real repos have a directory and are kept - including
    `product-app` and `product-website`, which are legitimately indexed at 11 rows
    each - while every worktree-shaped directory has a file, registered or not.

    ⚠️ Keeps the registry check as well. A REGISTERED worktree can live outside this walk root,
    and the two tests fail in different ways, which is the point of having both.
    """
    try:
        g = Path(path) / ".git"
        return g.is_file()
    except OSError:
        return False


def _in_other_worktree(path):
    """True when this directory IS, or sits inside, a worktree that is not the reader's."""
    if _is_worktree_dir(path):
        return True
    try:
        rp = Path(path).resolve()
    except OSError:
        return False
    for root in OTHER_WORKTREES:
        if rp == root or root in rp.parents:
            return True
    return False


def _as_reader_path(p):
    """Re-root an absolute path under the MAIN worktree when it sits inside ours."""
    try:
        return (READER_WS / Path(p).relative_to(WS)).as_posix()
    except (ValueError, TypeError):
        return Path(p).as_posix()


def render_row(a, indent=0):
    at = a["attrs"]
    rel = _linkable(a["path"])
    href = at.get("url") or rel
    title = a["title"] or a["path"].name
    head = "**[%s](%s)**" % (title, href) if href else "**%s**" % title
    shown = at.get("path")
    if shown:
        disp = shown if shown.startswith("C:") else (READER_WS / shown).as_posix()
        if shown.endswith("/"):
            disp = disp.rstrip("/") + "/"
    else:
        disp = _as_reader_path(a["path"])
    cols = [head, "`%s`" % disp]
    if at.get("also"):
        cols[-1] += " (+ `%s`)" % at["also"]
    cols.append(a["summary"] or "")
    return "%s- %s" % (" " * indent, " \u00b7 ".join(c for c in cols if c))


def render_orphan(o):
    head = "**[%s](%s)**" % (o["title"], o["href"]) if o.get("href") else "**%s**" % o["title"]
    return ("- \u26a0 **TARGET NOT ON DISK** - %s \u00b7 `%s` \u00b7 %s\n"
            "  \u21b3 *%s. Its authored text is held in `dev_docs_sections.json` until the file "
            "exists; nothing was dropped.*" % (head, o["path"], o["payload"], o["why"]))


def build():
    """(lines, problems) - the whole file, and anything that stopped it being clean."""
    arts = harvest()
    problems = []
    by_section = {}
    for a in arts:
        slug = a["attrs"].get("section")
        if slug not in SECTION_ORDER:
            problems.append("%s declares unknown section `%s`" % (a["path"].name, slug))
            continue
        if not a["summary"]:
            problems.append("%s carries a dev-doc marker but no <!-- summary: --> line"
                            % a["path"].name)
        by_section.setdefault(slug, []).append(a)

    orphans = {}
    for o in DATA.get("orphans", []):
        orphans.setdefault(o["section"], []).append(o)
        if Path(o["path"]).exists():
            problems.append("orphan RESOLVED - %s now exists; move its text onto the artifact "
                            "and delete the orphan entry (run --write to do it automatically)"
                            % o["path"])

    L = [BANNER, "", "# %s" % DATA.get("h1", "DEV-DOCS-INDEX"), "",
         DATA.get("header", ""), "",
         "**How this file is built.** Membership and every path are DERIVED: a doc appears "
         "here because it carries a `<!-- dev-doc: section=... -->` marker, and its path is "
         "wherever the file actually is - so a doc that moves takes its row with it. The "
         "one-line summary is authored and lives ON the artifact as `<!-- summary: ... -->`, "
         "which is why deleting this file loses nothing. Section groupings and their intro "
         "prose are authored in `.shared/scripts/dev_docs_sections.json`. Regenerate with "
         "`python .shared/scripts/dev_docs_index.py --write`.", "",
         "---", ""]

    for s in SECTIONS:
        rows = by_section.get(s["slug"], [])
        orph = orphans.get(s["slug"], [])
        L += ["## %s" % s["title"], ""]
        if s.get("intro"):
            L += [s["intro"], ""]
        if not rows and not orph:
            L += ["*Nothing carries `section=%s` today. That is a finding, not a formatting "
                  "gap.*" % s["slug"], ""]
        # parents first, each followed by its children, then the rest, all by declared order.
        kids = {}
        for a in rows:
            par = a["attrs"].get("parent")
            if par:
                kids.setdefault(par, []).append(a)
        top = [a for a in rows if not a["attrs"].get("parent")]
        top.sort(key=lambda a: int(a["attrs"].get("order", 0)))
        for a in top:
            L.append(render_row(a))
            for k in sorted(kids.get(a["path"].name, []),
                            key=lambda x: int(x["attrs"].get("order", 0))):
                L.append(render_row(k, indent=2))
        for k, v in kids.items():
            if k not in {a["path"].name for a in top}:
                problems.append("parent=%s named by %s is not in this section"
                                % (k, ", ".join(x["path"].name for x in v)))
        for o in sorted(orph, key=lambda x: x["order"]):
            L.append(render_orphan(o))
        L += [""]
        if s.get("rule_after"):
            L += ["---", ""]

    L += ["---", "", "## %s" % DATA.get("excluded_title", "Excluded (and why)"), "",
          DATA.get("excluded", ""), ""]
    return L, problems, arts


def cmd_check():
    _, problems, arts = build()
    print("dev-docs index - marker health")
    print()
    print("  artifacts carrying a dev-doc marker : %d" % len(arts))
    print("  orphan rows (no artifact on disk)   : %d" % len(DATA.get("orphans", [])))
    for o in DATA.get("orphans", []):
        print("     - %s  (%s)" % (o["path"], o["why"]))
    print("  problems                            : %d" % len(problems))
    for p in problems:
        print("     - %s" % p)
    print()
    if problems:
        print("  Each problem above is a row that will not render where it should.")
        return 1
    print("  every marker resolves to a known section, with a summary.")
    return 0


def _missing_declared_stores():
    """Declared nested product repos that are ABSENT from this checkout.

    ⭐ THE DIRECT TEST, AND IT NEEDS NO THRESHOLD. A partial tree is not a small drop - it is
    whole stores gone at once, and those stores are DECLARED in facets_vocabulary.json. Their
    absence is a fact about this checkout rather than a judgement about a count, which is why
    this runs first and the row-count comparison is only the net beneath it.

    A worktree is the ordinary way to land here: `git worktree add` checks out this repo and
    nothing else, so every nested product repo is missing and the generator sees a corpus less
    than half the size with no indication anything is wrong.
    """
    try:
        raw = json.loads((Path(__file__).resolve().parent
                          / "facets_vocabulary.json").read_text(encoding="utf-8"))
        repos = [n for n in raw.get("nested_repos", []) if n]
    except Exception:
        return []                        # no vocabulary, no claim - the count check still runs
    return [r for r in repos if not (WS / r).is_dir()]


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--allow-shrink", action="store_true",
                    help="write even though the index would lose rows - for a genuine "
                         "deletion, never to get past a partial tree")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        return selftest()
    if not DATA:
        # ⛔ NO SHAPE MEANS WRITE NOTHING. With no sections every artifact is "unknown section"
        # and an unguarded --write would replace the index with an empty skeleton - a generator
        # erasing the map because its vocabulary file was missing.
        print("dev-docs index: no %s - nothing generated, nothing on disk touched."
              % DATA_FILE.name)
        return 0
    if a.check:
        return cmd_check()
    if a.write:
        # Self-clearing: a resolved orphan is migrated rather than reported, so it can
        # never again be the reason this index refuses to write. See the function.
        for line in migrate_resolved_orphans():
            print("   MIGRATED: %s" % line)
    lines, problems, arts = build()
    # ⛔ A SCAN THAT FINDS NOTHING IS A BROKEN SCAN, NOT AN EMPTY CORPUS. Every row lives on an
    # artifact, so a checkout missing them - a partial clone, a wrong cwd, a walk that hit a
    # permissions error - would otherwise regenerate this file as sixteen empty headings and
    # destroy the map. knowledge_pages.py declines for the same reason when its tree is absent:
    # for a READER "detects nothing" is right; for a WRITER the equivalent is to refuse, loudly.
    if not arts and OUT.exists():
        print("dev-docs index: the scan found ZERO marked artifacts while %s exists."
              % OUT.name)
        print("   That is a broken scan, not an empty corpus - refusing to overwrite the map.")
        return 1
    new = "\n".join(lines).rstrip("\n") + "\n"
    old = OUT.read_text(encoding="utf-8", errors="replace") if OUT.exists() else None

    # ⛔ THE GUARD ABOVE FIRES AT ZERO, AND A PARTIAL TREE DOES NOT PRODUCE ZERO. Found by o1,
    # 2026-09-08, from a live loss: a session's commit touched a `dev-doc:`-marked file, the
    # index regenerated as a side effect from a tree without the nested product repos, and 38
    # real rows were deleted - every product-app/docs and product-website/docs spec,
    # the o6 keyword plan, the quiz, the script-writing research, and an artifact whose marker
    # o1 had added an hour earlier precisely to get it indexed. Reproduced here: a worktree
    # yields 47 artifacts where the full checkout yields 85, and the tool printed
    # "Fix: dev_docs_index.py --write" - inviting it.
    #
    # ⭐ THE REASONING OF THE ZERO GUARD WAS ALREADY RIGHT AND ITS TRIGGER WAS TOO NARROW. "For
    # a READER detects-nothing is right; for a WRITER the equivalent is to refuse, loudly." A
    # 46% shrink is the same event as a zero, arriving quietly.
    #
    # ⛔ WHY THIS IS WORSE THAN THE TWO EARLIER FALSE ALL-CLEARS ON THIS FILE. Phantom rows were
    # noise anyone could see. This DELETES real rows, looks like an ordinary regeneration, and
    # the session that caused it gets no signal - so a doc can be marked, landed, verified
    # indexed, and silently de-indexed hours later by an unrelated commit.
    # ⭐ THE PUSHBULLET SESSION'S ADDITION, 2026-09-08, and it earns its line: they watched the
    # artifact count go 171 -> 61 -> 47 across three runs and said "nothing in its output
    # treated that as a fault". A refusal only speaks when someone writes. This prints on EVERY
    # run, so a missing root is visible to a read-only check too - which is how the partial tree
    # would have announced itself before their commit rather than after o1 found the loss.
    _roots = {}
    for _a in arts:
        try:
            _rel = Path(_a["path"]).resolve().relative_to(WS.resolve()).parts
        except Exception:
            _roots["(memory)"] = _roots.get("(memory)", 0) + 1
            continue
        _roots[_rel[0] if len(_rel) > 1 else "(workspace root)"] = \
            _roots.get(_rel[0] if len(_rel) > 1 else "(workspace root)", 0) + 1
    if _roots:
        print("   markers per root: %s"
              % ", ".join("%s %d" % (k, v) for k, v in sorted(_roots.items(),
                                                              key=lambda kv: -kv[1])[:8]))

    stores_missing = _missing_declared_stores()
    old_rows = len(re.findall(r"^- \*\*", old or "", re.M))
    shrink = old_rows - len(arts)
    if a.write and not a.allow_shrink and (stores_missing or shrink > 0):
        print("\ndev-docs index: REFUSING to write - this looks like a PARTIAL TREE.")
        if stores_missing:
            # The direct test, and it beats any threshold: the stores are DECLARED in the facet
            # vocabulary, so their absence is a fact about this checkout, not a judgement.
            print("   declared stores missing from this checkout: %s"
                  % ", ".join(sorted(stores_missing)[:6]))
        if shrink > 0:
            # ⭐ THRESHOLD SET FROM HISTORY, NOT TASTE. Across the last 20 revisions of this
            # file the count moved +1 to +4, and the ONLY decrease was a -24 that was itself
            # almost certainly this bug. The index has never legitimately shrunk, so any
            # decrease is worth one sentence before it is written.
            print("   %s currently lists %d artifact(s); this run found %d - a drop of %d."
                  % (OUT.name, old_rows, len(arts), shrink))
        print("   Regenerate from the main checkout, which holds the nested product repos.")
        print("   A genuine deletion? Re-run with --allow-shrink; it stays in the history as")
        print("   the claim that you looked.")
        return 1
    for p in problems:
        print("   PROBLEM: %s" % p)
    if problems and a.write:
        print("\n  Refusing to write while a marker is unresolved - fix the above first.")
        return 1
    if old == new:
        print("dev-docs index - %d artifact(s), %d section(s): the file matches the corpus."
              % (len(arts), len(SECTIONS)))
        return 0
    if a.write:
        OUT.write_text(new, encoding="utf-8", newline="")
        print("dev-docs index - wrote %s (%d artifacts, %d sections, %d orphan rows)"
              % (OUT.name, len(arts), len(SECTIONS), len(DATA.get("orphans", []))))
        return 0
    # ⛔ AND THE READ-ONLY RUN MUST NOT RECOMMEND THE DESTRUCTIVE ACT. The refusal above only
    # speaks to someone who already typed --write; this line is what a session READS FIRST, and
    # it was saying "Fix: --write" from a partial tree - the tool naming the command that
    # deletes the rows. That is how the 04:57 loss happened: the operator did what the output
    # told them to.
    if stores_missing or shrink > 0:
        print("dev-docs index - this tree is PARTIAL; %s would lose %d row(s). Do NOT --write "
              "from here - regenerate from the main checkout." % (OUT.name, max(shrink, 0)))
        return 1
    print("dev-docs index - WOULD CHANGE %s (%d artifacts). Fix: dev_docs_index.py --write"
          % (OUT.name, len(arts)))
    return 1


def migrate_resolved_orphans():
    """Move a resolved orphan's authored text onto its artifact, then drop the orphan.

    ⛔ WHY THIS IS AUTOMATIC AND NOT A REPORTED PROBLEM. An orphan row exists to hold a
    summary for an artifact that does not exist yet. The moment the artifact appears, the
    row has done its job - but nothing was obliged to notice, so it sat there. And because
    an unresolved marker makes this generator REFUSE to write, one stale row froze the
    whole index.

    Measured 2026-09-08: the row for PWA-SOURCE-OF-TRUTH.md resolved on 2026-08-11 and
    nobody cleared it, so DEV-DOCS-INDEX.md could not accept a single new artifact for
    four weeks. The index header still read "Last updated: 2026-08-11" - the last day a
    write succeeded. o9 then measured the other half: NOTHING RAN THIS SCRIPT AT ALL
    (now a report-only step in morning_self_heal.py, 936d62b). Two independent causes,
    one symptom.

    ⭐ THE SHAPE WORTH REMEMBERING: a guard that keeps firing after its cause is gone is
    indistinguishable from a guard that is working. It prints a confident, accurate
    diagnosis every run. The fix is not a better message - it is removing the state that
    can be stale, by making the resolution the same act as the detection.

    Returns a list of human-readable lines describing what moved. Only ever called under
    --write; a dry run still reports the orphan as a problem so nothing changes silently.
    """
    moved = []
    remaining = []
    for o in DATA.get("orphans", []):
        target = Path(o["path"])
        if not target.exists():
            remaining.append(o)
            continue
        try:
            body = target.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            remaining.append(o)
            moved.append("could NOT read %s (%s) - orphan kept" % (target.name, exc))
            continue

        head = body.split("\n# ")[0]
        if SUMMARY.search(head):
            # The artifact already says it better than the orphan could. Drop the row
            # rather than overwrite an author's line with a stale one.
            moved.append("%s already carries its own summary - orphan row dropped"
                         % target.name)
            continue

        block = []
        if "dev-doc: section" not in head:
            block.append("<!-- dev-doc: section=%s order=%s -->"
                         % (o["section"], o.get("order", 50)))
            if o.get("title"):
                block.append("<!-- dev-doc-title: %s -->" % o["title"])
        block.append("<!-- summary: %s -->" % o["payload"].replace("-->", "--&gt;"))
        target.write_text("\n".join(block) + "\n" + body, encoding="utf-8", newline="")
        moved.append("moved the summary onto %s and dropped the orphan row" % target.name)

    if len(remaining) != len(DATA.get("orphans", [])):
        DATA["orphans"] = remaining
        DATA_FILE.write_text(json.dumps(DATA, indent=1, ensure_ascii=False) + "\n",
                             encoding="utf-8", newline="")
    return moved


def selftest():
    ok = True

    def t(label, cond):
        nonlocal ok
        print("  [%s] %s" % ("OK " if cond else "FAIL", label))
        ok &= bool(cond)

    print("dev_docs_index selftest")
    t("the authored shape loaded", bool(SECTIONS))
    t("section slugs are unique", len(SECTION_ORDER) == len(SECTIONS))
    t("every section has a title", all(s.get("title") for s in SECTIONS))

    blk = ("<!-- dev-doc: section=x order=20 parent=p.md -->\n"
           "<!-- dev-doc-title: A Title -->\n"
           "<!-- summary: line one\nline two. **Status: planned.** -->\n")
    mk = read_markers(blk)
    t("the block we write is the block we read", bool(mk))
    t("...attrs round-trip", mk["attrs"] == {"section": "x", "order": "20", "parent": "p.md"})
    t("...the title round-trips", mk["title"] == "A Title")
    # ⭐ A WRAPPED SUMMARY MUST COLLAPSE TO ONE LINE, or a row breaks the bullet it lives in.
    t("...a wrapped summary collapses to one line",
      mk["summary"] == "line one line two. **Status: planned.**")
    t("no marker is None, not an empty dict", read_markers("# nothing here") is None)
    t("a marker QUOTED inline (a table cell, a sentence) is not a declaration",
      read_markers("| 80 docs | each carries `<!-- dev-doc: section=x -->` |") is None)
    t("...but one at the start of a line is", read_markers(blk) is not None)

    # ⛔ THE FAILURE THAT MADE THIS A VIEW: a row pointing at a directory the file left. The
    # path is derived, so it cannot say anything but where the file is.
    fake = {"path": WS / "docs" / "specs" / "x.md", "title": "X", "summary": "*Spec* - s.",
            "attrs": {"section": "a", "order": "10"}}
    t("a repo-internal artifact renders a clickable relative link",
      "(docs/specs/x.md)" in render_row(fake))
    out = render_row({"path": MEM / "y.md", "title": "Y", "summary": "s",
                      "attrs": {"section": "a", "order": "10"}})
    t("an artifact OUTSIDE this repo renders no link (it would not open)",
      out.startswith("- **Y** \u00b7") and "](" not in out)
    t("...but still carries its absolute path", str(MEM.as_posix()) in out)
    t("an authored url= overrides the derived link",
      "(https://e.example/x)" in render_row({**fake, "attrs": {"section": "a", "order": "1",
                                                               "url": "https://e.example/x"}}))
    # READER_WS, not WS: an authored path= is still re-rooted to where the READER opens it.
    # The property under test is unchanged - an authored path overrides the derived one - only
    # the root it is rendered against moved, which is the fix this fixture now pins.
    t("an authored path= overrides the shown path (a row that points at a folder)",
      "`%s/product_page_1/`" % READER_WS.as_posix()
      in render_row({**fake, "attrs": {"section": "a", "order": "1",
                                       "path": "product_page_1/"}}))

    # ⛔ AN ORPHAN MUST BE LOUD. A row whose artifact is gone used to just sit there reading
    # like every other row; silently dropping it instead would be the data loss this conversion
    # was told to avoid.
    o = render_orphan({"title": "T", "path": "C:/gone.md", "payload": "*x* - y",
                       "href": None, "why": "not present"})
    t("an orphan row is rendered, and marked", "TARGET NOT ON DISK" in o and "*x* - y" in o)

    # ⛔ NEGATIVE CONTROL, and the only test here that can see a destructive bug. Every row
    # lives on an artifact, so a scan that reaches none of them looks exactly like "the corpus
    # is empty" - and the honest-looking response, writing what you found, erases the map.
    if OUT.exists():
        real, before = harvest, OUT.read_text(encoding="utf-8", errors="replace")
        try:
            globals()["harvest"] = lambda: []
            argv, sys.argv = sys.argv, ["dev_docs_index.py", "--write"]
            rc = main()
        finally:
            globals()["harvest"], sys.argv = real, argv
        t("an empty harvest REFUSES rather than blanking the index", rc == 1)
        t("...and the file on disk is untouched",
          OUT.read_text(encoding="utf-8", errors="replace") == before)

    t("the banner names the generator and forbids hand-editing",
      "GENERATED by .shared/scripts/dev_docs_index.py" in BANNER and "do not hand-edit" in BANNER)
    print("\nselftest %s" % ("PASSED" if ok else "FAILED"))
    return 0 if ok else 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:
        print("dev-docs index: %s" % e, file=sys.stderr)
        sys.exit(2)
