#!/usr/bin/env python3
"""Telling a guard the difference between DOING a thing and DESCRIBING it. One implementation.

<!-- route-tags: guard false positive description instance mention heredoc commit message
     generated template correspondence self-reference -->

⛔ EIGHT INSTANCES IN ONE DAY, 2026-08-17, across seven files:

  1. `block_retired_path` refused a commit whose MESSAGE explained the retired path
  2. `facets` tagged the cornerstone TEMPLATE as a doc about external_provider, because its examples used external_provider
  3. `knowledge_gate`'s overlap check read a REPLY as a duplicate of the message it replied to
  4. `owns_guard` refused the GENERATED browse page for "restating" a path it exists to link to
  5. `owns_guard` would have owned the template's own `<vendor>` placeholders
  6. `block_shared_tree_ops` blocked its own COMMIT MESSAGE, which explains what it forbids
  7. `block_shared_tree_ops` blocked its own TEST FILE, which must contain the forbidden strings
  8. `commitment_guard`'s attestation quoted the bad line, and a content check read the quote

⭐ ONE SHAPE: a guard matches TEXT, and text that DESCRIBES the forbidden thing contains it. The
author cannot see it, because at authoring time the description is obviously not an instance.

⭐ AND IT WAS SOLVED, SEPARATELY, FOUR TIMES - each fix private to one file, so the fifth guard
repeated the defect with the answer sitting four files away. **A workspace that solves a problem
and does not centralise the solution pays for it again on every recurrence.** Hence this module.

Two questions, two functions:

    executable_part(cmd)   what a shell will actually RUN, with prose removed
    is_derived(text)       whether a document is a view/template/thread rather than a claim
"""
import re

# ---- 1. commands -------------------------------------------------------------------------
# Places PROSE lives inside a shell command. Everything here is text a human wrote for a human;
# none of it is executed, so none of it should be matched.
_HEREDOC = re.compile(r"<<-?'?(\w+)'?.*?\n\1", re.S)
_MSG_QUOTED = re.compile(r"-(?:m|F)\s+(['\"])(?:\\.|(?!\1).)*\1", re.S)
_MSG_TOKEN = re.compile(r"-(?:m|F)\s+\S+")
_COMMENT = re.compile(r"#[^\n]*")
# ⛔ `echo` IS NOT STRIPPED, deliberately. It looks like prose and is not: `echo "<cmd>" | sh`
# is a working bypass, and an agent echoing a retired tool name is usually reaching for it.
#
# ⭐ THE RULE THIS SETTLED: a shared helper must be the INTERSECTION of what each caller needs,
# never the union. Stripping echo helped the guard I wrote it for and silently broke
# block_retired_path, whose own test caught it - measured 2026-08-17, `echo mcp__<vendor>__list`
# stopped being refused. Generalising a fix is only safe against every existing caller's tests.


def executable_part(cmd):
    """The command with everything a shell will not execute stripped out.

    ⛔ Match against THIS, never the raw command. `git commit -m "never run git stash"` contains
    the string a stash guard looks for, and blocking it stops the workspace from documenting its
    own rules - which is how a rule stops being written down at all.
    """
    if not cmd:
        return ""
    s = _HEREDOC.sub(" ", cmd)
    s = _MSG_QUOTED.sub(" ", s)
    s = _MSG_TOKEN.sub(" ", s)

    s = _COMMENT.sub(" ", s)
    return s


# ---- 2. markers --------------------------------------------------------------------------
# ⭐ ONE DEFINITION OF THE route-tags MARKER. Three modules had their own copy - route.py,
# knowledge_gate.py and knowledge_pages.py - and all three omitted re.S, so `.` never matched a
# newline and a WRAPPED marker was invisible to every one of them.
#
# ⛔ MEASURED 2026-08-18: the gate refused a doc for being unreachable while its route-tags line
# sat in the file, correct, wrapped across two lines at this workspace's own 100-column
# convention. The refusal was RIGHT in effect - route.py could not have found it either - which
# is the only reason it was caught rather than shipping as a silently unfindable doc.
#
# ⭐ A MARKER FORMAT IS A CONTRACT BETWEEN EVERY TOOL THAT READS IT
# (memory/marker_format_is_a_contract.md). Three private copies is three chances to disagree,
# and the workspace's own line-wrapping convention was enough to break all three at once.
ROUTE_TAGS = re.compile(r"<!--\s*route-tags:\s*(.+?)\s*-->", re.S)


# ---- 3. documents ------------------------------------------------------------------------
# ⛔ TWO SHAPES, because a generated file does not have to use OUR banner. o9L21 measured three
# codesight code-maps that `is_derived` called authored: CODESIGHT.md ends with
# `_Generated by [codesight](...)_` in markdown italics, and its two companion sections carry no
# banner at all. A labelling pass trusting this would have hand-labelled generated views - the
# exact error the pass was told to avoid, waved through by the helper meant to prevent it.
#
# ⭐ The generalisation: WE control our own generators and can mandate a marker; we do NOT
# control other tools', so recognising only our own shape means every foreign generator reads as
# authored. Path is the reliable signal there - a directory a tool owns is a stronger claim than
# a banner we hoped it would print.
_GENERATED = re.compile(r"<!--\s*GENERATED by|^_?Generated by \[", re.I | re.M)
_GEN_DIR = re.compile(r"[/\\]\.codesight[/\\]", re.I)
_TEMPLATE = re.compile(r"<!--\s*template\b|^#\s+\S.*\btemplate\b", re.I | re.M)
_CORRESPONDENCE = re.compile(r"<!--\s*correspondence:", re.I)
_TEST = re.compile(r"^(test_|.*[/\\]test_)", re.I)
# A placeholder is a shape, not a value: <vendor>, <slug>, _example, YOUR-KEY-HERE.
PLACEHOLDER = re.compile(r"<[^>\s]{2,}>|_example|\bYOUR[-_][A-Z]+\b")


def is_derived(text, path=None):
    """(bool, reason) - is this a VIEW, a FORM, a THREAD or a TEST rather than a claim?

    ⭐ THE COMMON PROPERTY, and the reason these four belong together: none of them can DRIFT
    independently of something else.

      - a GENERATED page is recomputed; if it is wrong you regenerate it, never edit it
      - a TEMPLATE's examples are shapes to be replaced, not values to be trusted
      - a REPLY shares its subject's vocabulary BY DEFINITION - that is what a thread is
      - a TEST must contain the exact strings it exercises, or it tests nothing

    So a content check has nothing to protect in any of them, and firing there produces a
    refusal the author cannot satisfy without damaging the artifact.
    """
    p = str(path or "")
    if _GEN_DIR.search(p.replace("\\", "/")):
        return True, "inside a generator's own directory - the tool owns every file in it"
    if _GENERATED.search(text or ""):
        return True, "generated view - regenerate it, never edit it"
    if _CORRESPONDENCE.search(text or ""):
        return True, "correspondence - a thread shares its subject's words by definition"
    if _TEMPLATE.search(text or ""):
        return True, "template - its examples are shapes, not values"
    if _TEST.search(p.replace("\\", "/").split("/")[-1]):
        return True, "test - it must contain the strings it exercises"
    return False, ""


def selftest():
    ok = True

    def t(name, cond):
        nonlocal ok
        ok = ok and bool(cond)
        print("  [%s] %s" % ("OK " if cond else "FAIL", name))

    STASH = "git " + "sta" + "sh"
    t("a -m message is not executable",
      STASH not in executable_part('git commit -m "never run %s here"' % STASH))
    t("a heredoc body is not executable",
      STASH not in executable_part("git commit -F - <<'EOF'\nnever %s\nEOF" % STASH))
    t("a trailing comment is not executable",
      STASH not in executable_part("git status  # not %s" % STASH))
    t("the real command survives", STASH in executable_part("%s -u" % STASH))
    t("a named dotfile path survives",
      ".shared/x.py" in executable_part("git add .shared/x.py"))
    t("generated is derived", is_derived("<!-- GENERATED by pages.py -->")[0])
    t("correspondence is derived", is_derived("<!-- correspondence: from=o9 to=o10 -->")[0])
    t("a test file is derived", is_derived("x", "a/test_thing.py")[0])
    t("an ordinary doc is NOT derived", not is_derived("# A note\n\nfacts.", "a/note.md")[0])
    t("placeholders are recognised", PLACEHOLDER.search("`.shared/secrets/<vendor>-key.txt`"))
    t("a real value is not a placeholder",
      not PLACEHOLDER.search("`.shared/secrets/external-provider-api-key.txt`"))
    print("\nselftest %s" % ("PASSED" if ok else "FAILED"))
    return 0 if ok else 1


if __name__ == "__main__":
    import sys
    sys.exit(selftest())
